server:
  port: 10030

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes: # 路由配置
        - id: user-service # 路由 id
          uri: lb://user-service # 路由目标地址
          predicates: # 路由条件
            - Path=/user/** # 匹配的请求路径, 达到这个条件就进入这个路由
        - id: blog-service
          uri: lb://blog-service
          predicates:
            - Path=/blog/**
        - id: captcha-service
          uri: lb://captcha-service
          predicates:
            - Path=/captcha/**
