server:
  port: 443

spring:
  application:
    name: captcha-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    # RabbitMq 集群地址 zmbdp -> 用户名； Hf@173503494 -> 密码； spring-cloud-blog -> 虚拟机名称
    addresses: amqp://zmbdp:Hf173503494@127.0.0.1:5672/spring-cloud-blog
    listener:
      simple:
        acknowledge-mode: manual # 配置为手动确认模式


logging:
  file:
    name: spring-cloud-blog-logs/captcha.log