server:
  port: 443

spring:
  application:
    name: captcha-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


logging:
  file:
    name: spring-cloud-blog-logs/captcha.log